title: Multi-Omics Data Analysis
description: STAT 992 Spring 2023
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template